### ISSUE TITLE
Cert Error

### ISSUE THREAD

**Issue by ShaunBaker** [salesforce-marketingcloud/FuelSDK-Node-SOAP#66] opened 2015-10-13 15:31 UTC
Hey

I am using [FuelSDK-Node](https://github.com/salesforcefuel/FuelSDK-Node) and getting an error.

Node: v4.1.2

Error message:

```
{ 
    [Error: unable to get local issuer certificate]
    code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
    errorPropagatedFrom: 'Request Module inside soapRequest' 
} 

Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1000:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:567:8)
```

Adding:

`rejectUnauthorized: false` to [Requests options](https://github.com/salesforcefuel/FuelSDK-Node-SOAP/blob/master/lib/fuel-soap.js#L62) corrects the issue but is probably not a long term solution.

**Comment by vernak2539** [comment] 2015-10-13 15:57
Hmm, likely an issue with the cert on our side. @dougwilson any idea? Saw this last year sometime

**Comment by dougwilson** [comment] 2015-10-13 16:03
Stack 6 is missing one of the intermediates, it looks like. @ShaunBaker , what is the Client ID you are using with this so I can confirm if this is the issue you are having?

**Comment by vernak2539** [comment] 2015-10-14 08:51
@ShaunBaker there seems to be an issue with one of the intermediate certificates on stack 6 (https://webservice.s6.exacttarget.com/). Is this what stack your requesting from? If so, I would continue to use your workaround for the time being (`rejectUnauthorized: false`). If not, let me know and we can dive deeper into the issue.

This will be fixed relatively quickly, but not at the moment due to the effects it may have across the board. Sorry for the inconvenience.

**Comment by ShaunBaker** [comment] 2015-10-14 09:49
Hey

Yes we are using the S6 stack.

Will continue with workaround. Please advise when this can be removed.

Thanks

**Comment by devinus** [comment] 2016-01-28 05:42
@vernak2539 Any idea if this is still an issue with stack 6? We may have to disable stack 6 in our product for now if it is.

**Comment by vernak2539** [comment] 2016-01-28 10:12
Hey @devinus, @dougwilson may be able to answer this a little better as he works with these people more than I.

**Comment by devinus** [comment] 2016-01-28 18:35
We've confirmed this is still an issue on stack 6.

**Comment by dougwilson** [comment] 2016-01-28 18:38
I've asked for an update just now.

**Comment by vernak2539** [comment] 2016-02-03 11:05
@devinus @ShaunBaker We've gotten an update. While there is no set timeline for the fix, they are going to be fixing this issue while updating the cert in the *second quarter of this year*. 

They have proposed an interim solution. Please email me at avernacchia (at) salesforce (dot) com, and I will put you in touch with the correct people.

**Closed** 2017-06-11 20:50 UTC
